/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AppAppRawMaterialIndexRouteImport } from './routes/_app/app.raw-material/index'
import { Route as AppAppProductIndexRouteImport } from './routes/_app/app.product/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/_app/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRawMaterialIndexRoute = AppAppRawMaterialIndexRouteImport.update({
  id: '/raw-material/',
  path: '/raw-material/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppProductIndexRoute = AppAppProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AppAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRouteWithChildren
  '/app/product/': typeof AppAppProductIndexRoute
  '/app/raw-material/': typeof AppAppRawMaterialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppRouteWithChildren
  '/app/product': typeof AppAppProductIndexRoute
  '/app/raw-material': typeof AppAppRawMaterialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app/app': typeof AppAppRouteWithChildren
  '/_app/app/product/': typeof AppAppProductIndexRoute
  '/_app/app/raw-material/': typeof AppAppRawMaterialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/product/' | '/app/raw-material/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/product' | '/app/raw-material'
  id:
    | '__root__'
    | '/'
    | '/_app/app'
    | '/_app/app/product/'
    | '/_app/app/raw-material/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppRoute: typeof AppAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/raw-material/': {
      id: '/_app/app/raw-material/'
      path: '/raw-material'
      fullPath: '/app/raw-material/'
      preLoaderRoute: typeof AppAppRawMaterialIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/product/': {
      id: '/_app/app/product/'
      path: '/product'
      fullPath: '/app/product/'
      preLoaderRoute: typeof AppAppProductIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AppAppRouteChildren {
  AppAppProductIndexRoute: typeof AppAppProductIndexRoute
  AppAppRawMaterialIndexRoute: typeof AppAppRawMaterialIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppProductIndexRoute: AppAppProductIndexRoute,
  AppAppRawMaterialIndexRoute: AppAppRawMaterialIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppRoute: AppAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
